config/routes.rb
Rails.application.routes.draw do

  root "screen#index" 
  resources :teams
  resources :matches
  resources :screen, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord

  belongs_to :local_team, class_name: "Team", foreign_key: "local_team_id"
  belongs_to :visiting_team, class_name: "Team", foreign_key: "visiting_team_id"


  MINIMUM_DURATION = 70 #minutes
  MAXIMUM_DURATION = 90 #minutes

  validate :end_date_after_start_date
  validate :team_dont_play_again_itself
  validates :local_team_id, presence: true
  validates :visiting_team_id, presence: true
  validates :local_team_points, inclusion: { in: 0..99 }
  validates :visiting_team_points, inclusion: { in: 0..99 }

  scope :today_matches, lambda { 
    where('started_at between ? and ? ', Time.now.beginning_of_day, Time.now.end_of_day ).
    order('started_at')
  }

  private

  def end_date_after_start_date
    return if ended_at.blank? || started_at.blank?

    if ended_at < started_at
      errors.add(:ended_at, "must be after the start date")
    elsif (started_at + MINIMUM_DURATION.seconds) > ended_at
      errors.add(:ended_at, "must be after the start date more than #{MINIMUM_DURATION} minutes")
    elsif (started_at + MAXIMUM_DURATION.seconds) > ended_at
      errors.add(:ended_at, "must be after the start date less than #{MAXIMUM_DURATION} minutes")
    end
  end

  def team_dont_play_again_itself
    if local_team_id == visiting_team_id
      errors.add(:local_team_id, "must be different from visiting_team_id")
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord

  has_many :local_matches, class_name: "Match", foreign_key: "local_team_id"
  has_many :visiting_matches, class_name: "Match", foreign_key: "visiting_team_id"
  
  validates :name, presence: true, uniqueness: true

  def can_be_destroyed?
    
    local_matches.empty? && visiting_matches.empty?

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.all
  end
  
  def show
    @match = Match.find(params[:id])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new({local_team_points: 0, visiting_team_points: 0})

  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to matches_path
    else
      render :new
    end
  end

  def update
      @match = Match.find(params[:id])
      if @match.update(match_params) 
        redirect_to matches_path, notice: 'Match was successfully updated'
      else
        render :edit
      end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy 
    redirect_to matches_path, notice: 'Match was successfully destroyed'
  end

  private

  def match_params
    params.require(:match).permit(:local_team_id, :visiting_team_id, :local_team_points, :visiting_team_points, :started_at, :ended_at)
  end  

end 

app/controllers/screen_controller.rb
class ScreenController < ApplicationController

  def index
    @matches = Match.today_matches
  end

end   

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to teams_path, notice: "Team was successfully created."
    else
      render :new
    end  
  end

  def show
    @team = Team.find(params[:id])
  end


  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path, notice: "Team was successfully updated."
    else
      render :edit
    end
  end


  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path, notice: "Team was successfully destroyed."
  end



  private

  def team_params
    params.require(:team).permit(:name)
  end 




end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

  def pretty_score(match)
    local_team_points = match.local_team_points || 0
    visiting_team_points = match.visiting_team_points || 0
    "#{local_team_points} - #{visiting_team_points}"
  end

  def pretty_date_time(datetime)
    if datetime
      datetime.strftime("%d/%m/%Y at %I:%M%p")
    else
      "Pending"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NeosystemsHandball</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="max-w-lg mx-auto mt-16 text-center rounded overflow-hidden shadow-lg p-10">
      <h1 class="mb-4 text-3xl font-black">Neosystem Handball Matches</h1>
    </div>

    <div class="p-10">
      <%= yield %>
    </div>
  </body>
</html>

app/views/matches/_form.html.erb
<div class="w-full max-w-xs">

<div class="bg-white shadow-xl rounded px-8 pt-6 pb-8 mb-4">
  
  <%= form_with(model: match) do |f| %>  
    <%= render "shared/errors", object: match %>

  <div class="mb-4">
    <div class="block text-gray-700 text-md font-bold mb-2">
      <%= f.label :local_team_id %>
    </div>
      <%= collection_select(:match, :local_team_id, Team.all, :id, :name) %>
    </div>

  <div class="mb-4">
    <div class="block text-gray-700 text-md font-bold mb-2">
      <%= f.label :visiting_team_id %>
  </div>
    <%= collection_select(:match, :visiting_team_id, Team.all, :id, :name) %>
  </div>

  <div class="mb-4">
    <div class="block text-gray-700 text-md font-bold mb-2">
      <%= f.label :local_team_points %>
    </div>
    <%= f.number_field :local_team_points, min:0 %>
  </div>

  <div class="mb-4">
    <div class="block text-gray-700 text-md font-bold mb-2">
      <%= f.label :visiting_team_points %>
    </div>
    <%= f.number_field :visiting_team_points, min:0 %> 
  </div>

  <div class="mb-4">
    <div class="block text-gray-700 text-md font-bold mb-2">
      <%= f.label :started_at %>
    </div>
    <%= f.datetime_field :started_at %>
  </div>

  <div class="mb-4">
    <div class="block text-gray-700 text-md font-bold mb-2">
      <%= f.label :ended_at %>
    </div>
    <%= f.datetime_field :ended_at %>  
  </div>

  <div class="mb-4">
    <%= f.submit class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %> 
  </div>

</div>
    
  <% end %>
  
</div>

app/views/matches/edit.html.erb
<h1>Edit</h1>

<%= render "form", match: @match %>

app/views/matches/index.html.erb
<h2 class="mb-4 text-4xl font-black">Matches</h2>

  <% if @matches.empty? %>
    <%= render "shared/banner", warning_text: "Please, add a new match" %>
  <% else %>

    <table class="min-w-full table-auto">
    <thead class="bg-gray-800 text-gray-300" >
      <tr>
        <th>Local team</th>
        <th>Visiting team</th>
        <th>Score</th>
        <th>Starts at</th>
        <th>Ends</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @matches.each do |match| %>
        <tr class="border-4 border-gray-200">
          <td><%= match.local_team.try(:name) %></td>
          <td><%= match.visiting_team.try(:name) %></td>
          <td><p><%= pretty_score(match) %></p></td>
          <td><%= pretty_date_time(match.started_at) %></td>
          <td><%= pretty_date_time(match.ended_at) %></td>
          <td>
                <%= link_to("Edit match", edit_match_path(match))%>
          </td>
          <td>
                <%= link_to "Delete", match_path(match), class: "button", method: :delete, data: {confirm: 'Are you sure?'} %>
          </td>

        </tr>
    </tbody>
      
      <% end %>
    </table>
      <% end %>
<br>
  <%= link_to "Add new match", new_match_path, 
    class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>

app/views/matches/new.html.erb
<div class="bg-grey-lighter min-h-screen flex flex-col">
  <div  class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
    <div class="bg-white px-6 py-8 rounded shadow-lg text-black w-full">

      <h2 class="mb-4 text-4xl font-black">New match</h2>

      <%= render "form", match: @match %>

    </div>
  </div>
</div>

app/views/screen/index.html.erb
<% if @matches.empty? %>
  <%= render "shared/banner", warning_text: "Sorry guys, no games scheduled for today" %>
<% else %>

  <h2 class="mb-4 text-4xl font-black">Now playing</h2>
  <table class="min-w-full table-auto">
    <thead class="bg-gray-800 text-gray-300" >
      <tr>
        <th>Local team</th>
        <th>Visiting team</th>
        <th>Score</th>
        <th>Starts at</th>
        <th>Ends</th>
      </tr>
    </thead>

    <tbody>
      <% @matches.each do |match| %>
        <tr class="border-4 border-gray-200">
          <td><%= match.local_team.try(:name) %></td>
          <td><%= match.visiting_team.try(:name) %></td>
          <td><p><%= pretty_score(match) %></p></td>
          <td><%= pretty_date_time(match.started_at) %></td>
          <td><%= pretty_date_time(match.ended_at) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/shared/_banner.html.erb
    <div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3" role="alert">
      <p class="font-bold"><%= warning_text%></p>
    </div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>